control_group_id: -3999467199
leads_log_group_id: -3999467199
include_private_note_in_welcome: false
invite:
  expire_hours: 168
  member_limit: 50
codes:
  TMTP:
    title_template: "{company} X TMT.AI (Partnership)"
    members: ["realcryptomoses", "ReeceMeyer", "TMTAIMANAGER", "TalentManager01", "Toripo"]
    admins: ["realcryptomoses", "TalentManager01", "TMTAIMANAGER"]
    welcome_message: |
      Welcome 👋
      Great connecting at TOKEN2049 Singapore.
      This chat is for our Track My Trades AI partnership.
  TMTE:
    title_template: "{company} X TMT.AI (Api Connection)"
    members: ["TMTAIMANAGER", "ReeceMeyer", "TalentManager01", "Toripo", "muzandv"]
    admins: ["realcryptomoses", "TalentManager01", "TMTAIMANAGER"]
    welcome_message: |
      Welcome 👋
      Great connecting at TOKEN2049 Singapore.
      This chat is for our Track My Trades AI exchange API connection.
  CCP:
    title_template: "Content Crusaders X {company} (Partnership - TOKEN2049)"
    members: ["dylantalentmanager", "TalentManager01", "realcryptomoses", "rosiedeliverablesmanager"]
    admins: ["realcryptomoses", "TalentManager01"]
    welcome_message: |
      Welcome 👋
      Content Crusaders × partnership (TOKEN2049) chat. Glad we met you in token2049 Singapore in 10/2026. Have a good token, will follow up with u at the end of the event.
  OP:
    title_template: "{company} X Operator AI (Discovery - T2049 10/26)"
    members: ["TalentManager01", "realcryptomoses", "TMTAIMANAGER", "Toripo"]
    admins: ["realcryptomoses", "TalentManager01", "TMTAIMANAGER", "Toripo"]
    welcome_message: |
      Welcome 👋
      Operator AI discovery (TOKEN2049).
  PR:
    title_template: "{company} X Prior Exchange (Discovery - T2049 10/26)"
    members: ["TalentManager01", "realcryptomoses", "TMTAIMANAGER", "cryptocrushshow"]
    admins: ["realcryptomoses", "TalentManager01", "TMTAIMANAGER", "cryptocrushshow"]
    welcome_message: |
      Welcome 👋
      Prior Exchange discovery (TOKEN2049).
